name: Terraform deploy ec2 in us-west-1 california
on:
  push:
    branches:
      - main  # Trigger on push to the main branch, adjust as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
      #          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/master'
        working-directory: terraform
        run: terraform apply "tfplan"
